services:
  app_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "8000:8000"
    networks:
      - dev_network
    volumes:
      - ./core:/app/core

networks:
  dev_network:
    driver: bridge
