version: "3.9"

services:
  mysql_server:
    image: mysql:8
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev_network

  app_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "8000:8000"
    depends_on:
      - mysql_server
    networks:
      - dev_network

volumes:
  db_data:

networks:
  dev_network:
    driver: bridge